### ISSUE TITLE
More API please :)

### ISSUE THREAD

**Issue by turt2live** [NuclearW/Farion#6]
Ideas for the API (discussed with NuclearW a LOOOONG while ago):
- A way to determine who is who in IRC (Example: "lol_im_turt" => turt2live in-game)
- A way to add custom IRC commands (Eg: .mycommand <args>)
- A way to add custom IRC commands via PM (Eg: PM the bot .login <user> <pass>)

Those are the 2 major ones I'd like, and if possible a way to determine if a player really is who they say they are. I'd tackle that with something like this:
- IRC nick wants to identify as player (in-game)
- If player not in-game, warn IRC user (no link)
- If player is in game, send them a message: "Type /irc confirm" to confirm that you are <irc nick> or ignore this message to decline"
- After 10 seconds if they do nothing decline the link. 
- Clearly if they enter the command, the nick and player are linked.

I'd further the system by adding some sort of NickServ authentication so a player doesn't have to constantly link their player name with their IC nick. (If logged in as the nick, do auto login)

Just some ideas of course. I do hope they get added so I can poke Farion with my plugins :)

**Comment by NuclearW** [comment]
I was in a skype call the other night with @shatteredbeam and we discussed moving Farion to PircBotX which will allow us to check for NickServ registration status, as a result I think we'll be able to move forward on the IRC-Game user linking system.  As for the rest, I'll see if it can be added properly abstracted from the current PircBot so that the transition won't ruin any work that gets done.

**Comment by turt2live** [comment]
That would be great, thanks :)

**Comment by turt2live** [comment]
Closing due to age (project appears inactive)
